#!/bin/bash

NOT_SOURCED=0

test "X$(basename -- "$0")" = "Xinstall-mix6000-linux" && NOT_SOURCED=1

if [ $NOT_SOURCED = 1 ]; then 
    echo
    echo "$(tput setaf 2)""Please source the script: source install-mix6000-linux""$(tput sgr 0)"
    echo
    exit 1
fi

CPWD=`pwd`
USERN=`whoami`

echo 
echo "$(tput setaf 2)""$(tput bold)""MIX6000 Installer:" "$(tput sgr 0)"
echo
echo "$(tput setaf 2)""Please enter your sudo password:""$(tput sgr 0)"
sudo -p "" -v
echo
echo "$(tput setaf 2)""Installing missing components on Ubuntu...""$(tput sgr 0)"
echo

sudo apt-get -y install git gawk wget diffstat unzip texinfo gcc-multilib build-essential chrpath libsdl1.2-dev xterm openjdk-7-jre wine kdiff3-qt gitk putty

git clone https://github.com/Angstrom-distribution/setup-scripts oe

# Enable caching of username and password
git config --global credential.helper cache

git config --global user.email "${USERN}@mixtelematics.com"
git config --global user.name "${USERN}"

# Open Embedded want bash (not dash)
sudo chsh -s /bin/bash `whoami`
sudo ln -s -f /bin/bash /bin/sh


# Add additional layers

cd ${CPWD}/oe/sources

echo
echo "$(tput setaf 2)""Adding META-ATMEL to layers.txt:""$(tput sgr 0)"

grep -q "meta-atmel,https://github.com/linux4sam/meta-atmel,master,HEAD" layers.txt || echo meta-atmel,https://github.com/linux4sam/meta-atmel,master,HEAD >> layers.txt

echo
echo "$(tput setaf 2)""Adding META-MIX6000 to layers.txt (GutHub login required):""$(tput sgr 0)"
echo


grep -q "meta-mix6000,https://github.com/MiXTelematics/meta-mix6000,master,HEAD" layers.txt || echo meta-mix6000,https://github.com/MiXTelematics/meta-mix6000,master,HEAD >> layers.txt


cd ${CPWD}/oe

MACHINE=sama5d3xek ./oebb.sh config sama5d3xek

# Tuning Open Embedded for ATMEL board

cd ${CPWD}/oe/conf

# Modifying bblayers.conf

echo
echo "$(tput setaf 2)""Modifying oe/conf/bblayers.conf:""$(tput sgr 0)"
echo

if [[ ! -f bblayers.conf.orig ]]; then
   cp bblayers.conf bblayers.conf.orig
fi

grep -q '${TOPDIR}/sources/meta-mix6000 \\' bblayers.conf || sed -i '/${TOPDIR}\/sources\/openembedded-core\/meta \\/a\  ${TOPDIR}\/sources\/meta-mix6000 \\' bblayers.conf
grep -q '${TOPDIR}/sources/meta-atmel \\' bblayers.conf || sed -i '/${TOPDIR}\/sources\/meta-mix6000 \\/a\  ${TOPDIR}\/sources\/meta-atmel \\' bblayers.conf

# Modifying local.conf

echo
echo "$(tput setaf 2)""Modifying oe/conf/local.conf:""$(tput sgr 0)"
echo

if [[ ! -f local.conf.orig ]]; then
   cp local.conf local.conf.orig
fi

grep -q '#INHERIT += "rm_work"' local.conf || sed -i 's/INHERIT += "rm_work"/#INHERIT += "rm_work"/' local.conf
grep -q 'NO32LIBS="1"' local.conf || sed -i '/INHERIT += "rm_work"/aNO32LIBS="1"' local.conf

echo
echo "$(tput setaf 2)""Installing DS-5 debugger (and Eclipse IDE)""$(tput sgr 0)"
echo

cd ${CPWD}
mkdir -p downloads
cd ${CPWD}/downloads

if [ ! -e DS500-BN-00019-r5p0-18rel0.tgz ]; then
    wget http://10.34.203.100/TOOLS/DS500-BN-00019-r5p0-18rel0.tgz
    wget http://10.34.203.100/TOOLS/workspacev1.3.tar.gz
    wget http://10.34.203.100/TOOLS/lintv1.1.tar.gz
    wget http://10.34.203.100/TOOLS/uboot.env
    tar xvzf DS500-BN-00019-r5p0-18rel0.tgz
fi

if [ ! -d ${CPWD}/ds-5 ]; then
    sudo ${CPWD}/downloads/install.sh --i-agree-to-the-contained-eula --force --destination ${CPWD}/ds-5 --no-interactive --quiet --skip-menu-install
fi

if [ ! -d ${CPWD}/workspace ]; then
    cd ${CPWD}
    tar xzf ${CPWD}/downloads/workspacev1.3.tar.gz
fi

if [ ! -d ${CPWD}/tools/lint ]; then
    cd ${CPWD}
    mkdir -p tools
    cd tools
    tar xzf ${CPWD}/downloads/lintv1.1.tar.gz
fi

echo
echo "$(tput setaf 2)""Adding CROSSGCC plugin to Eclipse""$(tput sgr 0)"
echo

cd ${CPWD}/ds-5/sw/eclipse
./eclipse -application org.eclipse.equinox.p2.director -noSplash -repository http://download.eclipse.org/releases/kepler -installIUs org.eclipse.cdt.build.crossgcc.feature.group


echo
echo "$(tput setaf 2)""$(tput bold)""Creating source workspace for MIX6000 development.""$(tput sgr 0)"
echo 

mkdir -p ${CPWD}/workspace
cd ${CPWD}/workspace

echo
echo "$(tput setaf 2)""Checking out MESA and MIX6000 (Develop) repositories:""$(tput sgr 0)"
echo 

if [ ! -d ${CPWD}/workspace/MESA ]; then
    git clone -b Develop https://github.com/MiXTelematics/MESA
fi

if [ ! -d ${CPWD}/workspace/mix6000 ]; then
    git clone -b Develop https://github.com/MiXTelematics/mix6000
fi

echo
echo "$(tput setaf 2)""Creating new MESA and MIX6000 branches for development""$(tput sgr 0)"
echo 
echo "$(tput setaf 2)""Please provide your MIX6000 development branch name (or Enter to branch from Develop): ""$(tput sgr 0)"
read BRANCHNAME
echo

if [ -z $BRANCHNAME ]; then
   BRANCHNAME="${USERN}-linux"
   NEWBRANCH=1
else
   NEWBRANCH=0
fi


cd ${CPWD}/workspace/MESA
MESA_DEV=0
test "$(git status | grep "On branch" | grep -o Develop)" = "Develop" && MESA_DEV=1
if [ $MESA_DEV = 1 ]; then 
    echo
    echo "$(tput setaf 2)""Branching (Develop) MESA ==> ($BRANCHNAME) MESA for your development""$(tput sgr 0)"
    echo

    if [ $NEWBRANCH = 1 ]; then 
       git branch $BRANCHNAME
    fi

    git checkout $BRANCHNAME 
fi

cd ${CPWD}/workspace/mix6000
MIX6000_DEV=0
test "$(git status | grep "On branch" | grep -o Develop)" = "Develop" && MIX6000_DEV=1
if [ $MIX6000_DEV = 1 ]; then 
    echo
    echo "$(tput setaf 2)""Branching (Develop) MESA ==> ($BRANCHNAME) MESA for your development""$(tput sgr 0)"
    echo
    
    if [ $NEWBRANCH = 1 ]; then 
       git branch $BRANCHNAME
    fi

    git checkout $BRANCHNAME  
fi

echo
echo "$(tput setaf 2)""OpenEmbedded environment setup.""$(tput sgr 0)"
echo 

cd ${CPWD}/oe

ENVIR=`ls | grep environment`

source ${ENVIR}

echo
echo "$(tput setaf 2)""$(tput bold)""Building MIX6000 SDK (and compiler) ... go make some coffee ...""$(tput sgr 0)"
echo 

# Should we rebuild meta-toolchain?

cd ${CPWD}/oe
if [ -d ${CPWD}/oe/build ]; then
cd build
	CHECK1=$(ls | grep tmp)
	if [ -z $CHECK1 ]; then
	   cd ${CPWD}/oe
	   bitbake mix6000-image -c populate_sdk
	else
	   cd ${CPWD}/oe/build/
	   cd $(ls | grep tmp)
	   CHECK2=$(ls deploy/sdk/ | grep toolchain)
	   if [ -z $CHECK2 ]; then
	       cd ${CPWD}/oe
	       bitbake mix6000-image -c populate_sdk
	   fi
	fi
else
   cd ${CPWD}/oe
   bitbake mix6000-image -c populate_sdk
fi

# Should we reinstall sdk?

if [ ! -d ${CPWD}/sdk ]; then
   cd ${CPWD}/oe/build/
   cd $(ls | grep tmp)
   cd deploy/sdk
   echo "${CPWD}/sdk" > stdin_sdk
   ./$(ls | grep toolchain) < stdin_sdk
fi

echo
echo "$(tput setaf 2)""$(tput bold)""Importing MIX6000 project into workspace""$(tput sgr 0)"
echo
echo "$(tput setaf 2)""$(tput bold)""Please IGNORE path not found errors...""$(tput sgr 0)"
echo 

cd ${CPWD}

# Import MIX6000 Project

$CPWD/ds-5/bin/eclipse -data $CPWD/workspace -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -import $CPWD/workspace/mix6000/project


cd ${CPWD}

echo 
echo "$(tput setaf 2)""$(tput bold)""Run: setup-mix6000-linux" "$(tput sgr 0)"
echo




